import{a as y,S as q,i as c}from"./assets/vendor-778245f4.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))g(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const u of n.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&g(u)}).observe(document,{childList:!0,subtree:!0});function i(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerpolicy&&(n.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?n.credentials="include":r.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function g(r){if(r.ep)return;r.ep=!0;const n=i(r);fetch(r.href,n)}})();function w(e,t){return y.get("https://newsapi.org/v2/everything",{params:{apiKey:"31d73c075bf1480facfc72f704139b7b",q:e,searchIn:"content",sortBy:"relevancy",pageSize:15,page:t}})}function d(){return{form:document.querySelector(".js-search-form"),wrapper:document.querySelector(".js-wrapper"),loader:document.querySelector(".js-loader"),newsBtn:document.querySelector(".js-news-btn"),modal:document.querySelector(".js-modal"),closeBtn:document.querySelector(".js-close-btn")}}function f(e){return e.map(t=>`
      <li class="list-item">
        <a class="list-item-link" href="${t.url}">
          <img class="list-item-img" src="${t.urlToImage}" alt="${t.title}" width="360" height="200" loading="lazy"">
          <div>
          <h3 class="list-item-title">${t.title}</h3>
          <p class="list-item-text">${t.description}</p>
          </div>
          <div class="author-block">
            <p class="list-item-author">Author: ${t.source.name}</p>
          </div>
        </a>
      </li>
        `).join("")}const p=d(),T={lines:18,length:13,width:22,radius:0,scale:1,corners:.5,speed:1,rotate:90,animation:"spinner-line-shrink",direction:1,color:"#59cf86",fadeColor:"transparent",top:"48%",left:"48%",shadow:"0 0 1px transparent",zIndex:2e9,className:"spinner",position:"absolute"},v=new q(T);function m(){v.spin(p.loader),p.loader.classList.remove("is-hidden")}function l(){v.stop(),p.loader.classList.add("is-hidden")}function $(){c.warning({title:"Warning",message:"Write request",position:"center"})}function b(){c.error({title:"Error",message:"Server error",position:"center"})}function L(e){c.info({title:"Hello",message:`We have found ${e} results`,position:"topRight"})}function j(){c.info({title:"Sorry",message:"It`s all results",position:"topRight"})}function S(){d().newsBtn.classList.add("is-hidden")}function B(e,t){return y.get("https://newsapi.org/v2/top-headlines",{params:{apiKey:"31d73c075bf1480facfc72f704139b7b",q:e,searchIn:"content",sortBy:"relevancy",pageSize:15,page:t,country:"us"}})}const E=d();function I(){E.modal.classList.add("modal-window-overlay")}function M(){E.modal.classList.add("is-hidden")}const s=d();let a=null,o=1;const R={root:null,rootMargin:"100px",threshold:1},k=function(e,t){e.forEach(i=>{i.isIntersecting&&(t.unobserve(i.target),H())})},h=new IntersectionObserver(k,R);s.form.addEventListener("submit",A);s.newsBtn.addEventListener("click",x);window.addEventListener("load",I);s.closeBtn.addEventListener("click",M);async function A(e){if(e.preventDefault(),S(),a=e.currentTarget.elements.delay.value.trim(),m(),!a)return l(),s.wrapper.innerHTML="",$();try{const t=await w(a);s.wrapper.innerHTML=f(t.data.articles),L(t.data.totalResults),o<t.data.totalResults/15&&h.observe(s.wrapper.lastElementChild)}catch{b()}finally{l()}e.target.reset()}async function H(){o+=1,m();try{const e=await w(a,o);s.wrapper.insertAdjacentHTML("beforeend",f(e.data.articles)),o<e.data.totalResults/15?h.observe(s.wrapper.lastElementChild):j()}catch{}finally{l()}}async function x(){S(),m(),M();try{const e=await B();s.wrapper.innerHTML=f(e.data.articles),L(e.data.totalResults),o<e.data.totalResults/15&&h.observe(s.wrapper.lastElementChild)}catch{b()}finally{l()}}
//# sourceMappingURL=commonHelpers.js.map
