import{a as b,S as w,i as u}from"./assets/vendor-778245f4.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const r of document.querySelectorAll('link[rel="modulepreload"]'))d(r);new MutationObserver(r=>{for(const n of r)if(n.type==="childList")for(const a of n.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&d(a)}).observe(document,{childList:!0,subtree:!0});function s(r){const n={};return r.integrity&&(n.integrity=r.integrity),r.referrerpolicy&&(n.referrerPolicy=r.referrerpolicy),r.crossorigin==="use-credentials"?n.credentials="include":r.crossorigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function d(r){if(r.ep)return;r.ep=!0;const n=s(r);fetch(r.href,n)}})();function p(t,e){return b.get("https://newsapi.org/v2/everything",{params:{apiKey:"31d73c075bf1480facfc72f704139b7b",q:t,searchIn:"content",sortBy:"relevancy",pageSize:15,page:e,Authorization:"31d73c075bf1480facfc72f704139b7b"}})}function m(){return{form:document.querySelector(".js-search-form"),wrapper:document.querySelector(".js-wrapper"),loader:document.querySelector(".js-loader")}}function h(t){return t.map(e=>`
      <li class="list-item">
        <a class="list-item-link" href="${e.url}">
          <img class="list-item-img" src="${e.urlToImage}" alt="${e.title}" width="360" height="200" loading="lazy"">
          <div>
          <h3 class="list-item-title">${e.title}</h3>
          <p class="list-item-text">${e.description}</p>
          </div>
          <div class="author-block">
            <p class="list-item-author">Author: ${e.source.name}</p>
          </div>
        </a>
      </li>
        `).join("")}const l=m(),L={lines:18,length:13,width:22,radius:0,scale:1,corners:.5,speed:1,rotate:90,animation:"spinner-line-shrink",direction:1,color:"#59cf86",fadeColor:"transparent",top:"48%",left:"48%",shadow:"0 0 1px transparent",zIndex:2e9,className:"spinner",position:"absolute"},g=new w(L);function y(){g.spin(l.loader),l.loader.classList.remove("is-hidden")}function c(){g.stop(),l.loader.classList.add("is-hidden")}function S(){u.warning({title:"Warning",message:"Write request",position:"center"})}function $(){u.error({title:"Error",message:"Server error",position:"center"})}function q(t){u.info({title:"Hello",message:`We have found ${t} results`,position:"topRight"})}const o=m();let i=null,f=1;const A={root:null,rootMargin:"100px",threshold:1},M=function(t,e){t.forEach(s=>{s.isIntersecting&&(e.unobserve(s.target),T())})},v=new IntersectionObserver(M,A);o.form.addEventListener("submit",I);async function I(t){if(t.preventDefault(),i=t.currentTarget.elements.delay.value.trim(),y(),!i)return c(),o.wrapper.innerHTML="",S();try{const e=await p(i);o.wrapper.innerHTML=h(e.data.articles),q(e.data.totalResults),v.observe(o.wrapper.lastElementChild)}catch{$()}finally{c()}t.target.reset()}async function T(){f+=1,y();try{const t=await p(i,f);o.wrapper.insertAdjacentHTML("beforeend",h(t.data.articles));const e=document.querySelector(".list-item:last-child");v.observe(e)}catch{}finally{c()}}
//# sourceMappingURL=commonHelpers.js.map
